// USERS ACTION TYPES
export const FETCH_USERS = "FETCH_USERS";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

// FINANCE ACTION TYPES
export const FETCH_BUDGET = "FETCH_BUDGET";
export const FETCH_BANK = "FETCH_BANK";
export const FETCH_EXPENSES = "FETCH_EXPENSES";
